name: Continuous Integration Tests

on: [push]

jobs:
  execute_black_linter_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install --no-cache-dir --upgrade -r requirements.txt
      - name: Execute the black linter
        run: black -l 100 -S . --check
      - name: Execute Tests
        run: pytest --cov=. test
